# config_cpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: 'europe-north1-docker.pkg.dev/fast-asset-447810-r9/repdocker/myimage'
